### ISSUE TITLE
Can we build the app using only personal apple account without team account?

### ISSUE THREAD

**Issue by mobilelifeful** [bagisto/opensource-ecommerce-mobile-app#10]
**Is your feature request related to a problem? Please describe.**

When trying to build for ios, it fail since it asks for team account 

**Describe the solution you'd like**
Building the ios app using just personal apple account.

**Describe alternatives you've considered**
Please share a ipa file for us to download and try out.

**Additional context**
Thank you.

**Comment by AnchitAndroidWorld** [comment]
Hey There,

Due to the restrictions from apple security we cannot create a public universal ipa link that everyone can download and check on their phones.

Further, corresponding to building the iOS app using just personal apple account.
-> You can try this only if you have a apple developer account as that is required by the apple team to deploy a debug version to a limited number of devices.

This is something not exactly in our scope and this needs to be done on the developer end that wants to try, run and contribute to this project further.

Regards,
