### ISSUE TITLE
UI Displays Shimmering Blank Screen and GraphQL Errors in Bagisto E-Commerce Mobile App

### ISSUE THREAD

**Issue by medlemine-djeidjah** [bagisto/opensource-ecommerce-mobile-app#17]
Description:

We are experiencing a critical issue with the Bagisto e-commerce mobile app. Upon launching the app, the user interface displays a shimmering blank screen and fails to load any content. Additionally, several GraphQL errors are being logged in the console.

Actual Behavior:

The UI is stuck on a shimmering blank screen.
GraphQL errors are present in the logs.

Screenshots:

![WhatsApp Image 2024-09-02 at 14 13 47_d9996cf1](https://github.com/user-attachments/assets/b2a4bc30-da70-48ed-83dc-df70e0597903)

![image](https://github.com/user-attachments/assets/fd30723c-e27f-4235-82ba-1f8b53326028)

![image](https://github.com/user-attachments/assets/4acb7141-ad52-4c18-a6da-1e3d030a4b39)

Environment:

flutter : 3.10.1
Bagisto : 2.0.0
bagisto_graphql:2.0.0

**Comment by vivek-webkul** [comment]
Hi @medlemine-djeidjah ,

Greetings for the day! Hope you are doing great.

Please cross-check that you have made the correct entry for the headless ModuleServiceProvider in the config/concord.php file:
\Webkul\GraphQLAPI\Providers\ModuleServiceProvider::class,

Like:

![config_concord](https://github.com/user-attachments/assets/dc9a16c6-c367-4b5d-bb91-f517f55aa121)


Checked the installation guide for the same as well:
https://github.com/bagisto/headless-ecommerce/tree/v2.0.2?tab=readme-ov-file#2-installation

The above issue will be fixed by doing this configuration, In case you face any other issues or doubts feel free to ask us!

Thanks & Regards,
Vivek Sharma
Bagisto Support Team

**Comment by medlemine-djeidjah** [comment]
Hi @Vivek-Sharma,

Thank you for your  assistance. I wanted to let you know that the issue has been resolved by upgrading to bagisto-graphQL 2.0.2. and configuring it following the guide you provided .Your guidance was very helpful in ensuring everything is configured correctly.

I appreciate your support and will definitely reach out if any other issues arise.

Thanks again!

Best regards,
